const domains = [
  '4dsply.com',
  'aarth.com',
  'ab4hr.com',
  'ad4game.com',
  'adcash.com',
  'adexc.net',
  'adexchangecloud.com',
  'adexchangeprediction.com',
  'adf.ly',
  'adform.net',
  'admob.com',
  'adnetworkperformance.com',
  'adnxs.com',
  'adrecreate.com',
  'adscpm.net',
  'adstimer.com',
  'altadefinizione01.black',
  'anetwork.ir',
  'appcloudprotected.com',
  'aragontrack.com',
  'ato.mx',
  'avito.ru',
  'backpage.com',
  'bankia.es',
  'bfads.net',
  'bitdefender.com',
  'blackfriday.com',
  'blogspot.fi',
  'boingboing.net',
  'clicksgear.com',
  'clicktabs.net',
  'clixsense.com',
  'cloudfront.net',
  'confirmed-profits.com',
  'disqus.com',
  'doubleclick.net',
  'doublepimp.com',
  'drom.ru',
  'encuentra24.com',
  'exoclick.com',
  'fortadpays.com',
  'fulltab.com',
  'gametop.com',
  'getadblock.com',
  'hilltopads.net',
  'hyperpromote.com',
  'idealista.com',
  'ijquery11.com',
  'ipg-online.com',
  'joomla.org',
  'juicyads.com',
  'junkmail.co.za',
  'keywordblocks.com',
  'kolesa.kz',
  'lichess.org',
  'locanto.in',
  'maha-media.com',
  'mama.cn',
  'mcafee.com',
  'media-rocks.com',
  'mgid.com',
  'mixplugin.com',
  'mymoneymakingapp.com',
  'mypayingads.com',
  'mytorrents.org',
  'newpoptab.com',
  'nextlnk8.com',
  'njuskalo.hr',
  'nuesearch.com',
  'offerreality.com',
  'olx.in',
  'olx.ro',
  'onclickads.net',
  'opera.com',
  'oreillyauto.com',
  'outbrain.com',
  'paruvendu.fr',
  'payu.in',
  'pdfconverterhq.com',
  'popads.net',
  'poptm.com',
  'pornhubpremium.com',
  'queryrouter.com',
  'redirectvoluum.com',
  'robinwidget.com',
  'royalads.net',
  'seloger.com',
  'semrush.com',
  'sh.st',
  'shoplocal.com',
  'slimspots.com',
  'smadav.net',
  'snapdo.com',
  'splix.io',
  'spotscenered.info',
  'startgo123.com',
  'surfearner.com',
  'terraclicks.com',
  'tgmgo.com',
  'theblackfriday.com',
  'thewhizmarketing.com',
  'thewhizproducts.com',
  'trackingclick.net',
  'tradeadexchange.com',
  'traffichaus.com',
  'tvplusnewtab.com',
  'utarget.ru',
  'vibbo.com',
  'vimeo.com',
  'vivanuncios.com.mx',
  'vodafone.it',
  'vppgamingnetwork.com',
  'wg-gesucht.de',
  'www-searching.com',
  'xb11766.com',
  'yieldtraffic.com',
  'zapmetasearch.com'
]

module.exports = {
  retrieve: function (cb) {
    cb(null, domains)
  },

  build: function (cb) {
    const transformedList = domains.map((item) => { return `'${item}'` }).join(', ')
    const rule = {
      condition: `(new Set([ ${transformedList} ])).has(SLD)`,
      consequent: null,
      description: 'exclude advertising platforms'
    }
    cb(null, rule)
  }
}
