module.exports = [ { condition: '(new Set([ \'baidu\', \'bing\', \'dogpile\', \'google\', \'ixquick\', \'kvasir\', \'searx\', \'sogou\', \'yahoo\', \'yandex\', \'youdao\' ])).has(SLD.split(\'.\')[0])',
    consequent: null,
    description: 'exclude search engines' },
  { condition: '(new Set([ \'githubusercontent\', \'ssl-images-amazon\', \'twimg\', \'ytimg\' ])).has(SLD.split(\'.\')[0])',
    consequent: null,
    description: 'exclude image stores' },
  { condition: '(new Set([ \'githubusercontent.com\' ])).has(TLD) || /amazonaws\\.com$/.test(SLD) || /herokuapp\\.com$/.test(SLD) || /tumblr\\.com$/.test(SLD) || /wordpress\\.com$/.test(SLD)',
    consequent: null,
    description: 'exclude content stores' },
  { condition: '(new Set([ \'baiducontent.com\', \'googleusercontent.com\', \'microsofttranslator.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude machine-translations' },
  { condition: '(new Set([ \'bilibili\', \'blogger\', \'blogspot\', \'craigslist\', \'facebook\', \'github\', \'imgur\', \'instagram\', \'linkedin\', \'livejournal\', \'medium\', \'pinterest\', \'quora\', \'slack\', \'stackoverflow\', \'twitter\', \'vk\', \'xvideos\', \'youku\', \'youtube\', \'ello\', \'nextdoor\' ])).has(SLD.split(\'.\')[0])',
    consequent: null,
    description: 'exclude platforms' },
  { condition: '(new Set([ \'messenger\', \'skype\', \'whatsapp\' ])).has(SLD.split(\'.\')[0])',
    consequent: null,
    description: 'exclude messaging application' },
  { condition: '(new Set([ \'t.co\' ])).has(SLD)',
    consequent: null,
    description: 'exclude redirection points' },
  { condition: '/^campaign-archive[0-9]+.com$/.test(SLD)',
    consequent: null,
    description: 'exclude campaign engines' },
  { condition: 'TLD === \'gov\' || /^go.[a-z][a-z]$/.test(TLD) || /^gov.[a-z][a-z]$/.test(TLD)',
    consequent: null,
    description: 'exclude all government sites' },
  { condition: '(new Set([ \'brave.com\' ])).has(SLD)',
    consequent: null,
    description: 'res ipsa loquitur' },
  { condition: '(new Set([ \'onclickads.net\', \'outbrain.com\', \'popads.net\' ])).has(SLD)',
    consequent: null,
    description: 'exclude advertising platforms' },
  { condition: '(new Set([ \'awkwardfamilyphotos.com\', \'diply.com\', \'feedly.com\', \'imdb.com\', \'reddit.com\', \'stackexchange.com\', \'superuser.com\', \'ycombinator.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude aggregators' },
  { condition: '(new Set([ \'360.cn\', \'alibaba.com\', \'aliexpress.com\', \'amazon.co.jp\', \'amazon.co.uk\', \'amazon.com\', \'amazon.de\', \'amazon.in\', \'ebay.com\', \'jd.com\', \'racerglovesusa.com\', \'rakuten.co.jp\', \'rei.com\', \'samsung.com\', \'taobao.com\', \'tmall.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude commerce sites' },
  { condition: '(new Set([ \'247exchange.com\', \'bitcointoyou.com\', \'bitgo.com\', \'bitx.co\', \'coinbase.com\', \'coinjar.com\', \'cubits.com\', \'quadrigacx.com\', \'zebpay.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude BTC exchanges' },
  { condition: '(new Set([ \'163.com\', \'naver.com\', \'pixnet.net\', \'sohu.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude news platforms' },
  { condition: '(new Set([ \'alipay.com\', \'amtrak.com\', \'android.com\', \'antigate.com\', \'apple.com\', \'audible.com\', \'bbsconstruction.ca\', \'bitgo.com\', \'booking.com\', \'card-data.com\', \'chase.com\', \'coccoc.com\', \'coinbase.com\', \'digitalocean.com\', \'docusign.net\', \'dreamhost.com\', \'dropbox.com\', \'duckduckgo.com\', \'entelo.com\', \'ethermine.org\', \'fastmail.com\', \'fc2.com\', \'fitbit.com\', \'flattr.net\', \'getaround.com\', \'getfinal.com\', \'gitlab.com\', \'hvaerminip.no\', \'icloud.com\', \'icoconvert.com\', \'ifttt.com\', \'instacart.com\', \'ipchicken.com\', \'ipv6-test.com\', \'keybase.io\', \'librato.com\', \'live.com\', \'mail.ru\', \'microsoft.com\', \'microsoftonline.com\', \'mlab.com\', \'nanopool.org\', \'netflix.com\', \'newrelic.com\', \'nicovideo.jp\', \'office.com\', \'ok.ru\', \'okcoin.com\', \'pagerduty.com\', \'paypal.com\', \'presents.social\', \'prometheus.io\', \'roomserviceparty.com\', \'royalbank.com\', \'ryver.com\', \'simplenote.com\', \'solanolabs.com\', \'soso.com\', \'steampowered.com\', \'storytel.no\', \'superhuman.com\', \'tdsecurities.com\', \'test-ipv6.com\', \'thecse.com\', \'toptal.com\', \'trakt.tv\', \'trycaviar.com\', \'upwork.com\', \'usefixie.com\', \'wpengine.com\', \'yelp.com\', \'zendesk.com\' ])).has(SLD)',
    consequent: null,
    description: 'exclude services' },
  { condition: true,
    consequent: 'SLD',
    description: 'the default rule' } ]
